# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
# This file is processed by `configtxgen`, invoked from `./byfn.sh generate`

---
Organizations:
    # SampleOrg defines an MSP using the sampleconfig.  It should never be used in production but may be used as a template for other definitions
    - &global
        Name: global
        ID: global-msp
        MSPDir: crypto-config/ordererOrganizations/global.svc.cluster.local/msp

        # Policies defines the set of policies at this level of the config tree
        # For organization policies, their canonical path is usually /Channel/<Application|Orderer>/<OrgName>/<PolicyName>
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('global-msp.member')"
            Writers:
                Type: Signature
                Rule: "OR('global-msp.member')"
            Admins:
                Type: Signature
                Rule: "OR('global-msp.admin')"

    - &org1
        Name: org1-msp
        ID: org1-msp
        MSPDir: crypto-config/peerOrganizations/org1.svc.cluster.local/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('org1-msp.admin', 'org1-msp.peer', 'org1-msp.client')"
            Writers:
                Type: Signature
                Rule: "OR('org1-msp.admin', 'org1-msp.client')"
            Admins:
                Type: Signature
                Rule: "OR('org1-msp.admin')"
        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used for cross org gossip communication.
            # Note, this value is only encoded in the genesis block in the Application section context
            - Host: peer0.org1.svc.cluster.local
              Port: 7051

    - &org2
        Name: org2-msp
        ID: org2-msp
        MSPDir: crypto-config/peerOrganizations/org2.svc.cluster.local/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('org2-msp.admin', 'org2-msp.peer', 'org2-msp.client')"
            Writers:
                Type: Signature
                Rule: "OR('org2-msp.admin', 'org2-msp.client')"
            Admins:
                Type: Signature
                Rule: "OR('org2-msp.admin')"
        AnchorPeers:
            - Host: peer0.org2.svc.cluster.local
              Port: 7051

Capabilities:
    # Set the value of the capability to true to require it.
    # Channel capabilities apply to both the orderers and the peers and must be supported by both.
    Channel: &ChannelCapabilities
        V1_4_3: true
        V1_3: false
        V1_1: false

    # Orderer capabilities apply only to the orderers, and may be safely used with prior release peers.
    Orderer: &OrdererCapabilities
        V1_4_2: true
        V1_1: false

    # Application capabilities apply only to the peer network, and may be safely used with prior release orderers.
    Application: &ApplicationCapabilities
        V1_4_2: true
        V1_3: false
        V1_2: false
        V1_1: false

Application: &ApplicationDefaults
    # This section defines the values to encode into a config transaction or genesis block for application related parameters

    # Organizations is the list of orgs which are defined as participants on the application side of the network
    Organizations:

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    # This section defines the values to encode into a config transaction or genesis block for orderer related parameters

    # Orderer Type: The orderer implementation to start, available types are "solo"
    OrdererType: solo

    Addresses:
        - orderer.global.svc.cluster.local:7050

    BatchTimeout: 2s                # The amount of time to wait before creating a batch

    BatchSize:                      # Controls the number of messages batched into a block
        MaxMessageCount: 10         # The maximum number of messages to permit in a batch
        AbsoluteMaxBytes: 99 MB     # The absolute maximum number of bytes allowed for the serialized messages in a batch.
        PreferredMaxBytes: 512 KB   # The preferred maximum number of bytes allowed for the serialized messages in a batch.

    # Organizations is the list of orgs which are defined as participants on the orderer side of the network
    Organizations:

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:            # What signatures must be included in the block from the orderer for the peer to validate it.
            Type: ImplicitMeta
            Rule: "ANY Writers"

Channel: &ChannelDefaults
    # This section defines the values to encode into a config transaction or genesis block for channel related parameters.
    Policies:
        Readers:                    # Who may invoke the 'Deliver' API
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:                    # Who may invoke the 'Broadcast' API
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:                     # By default, who may modify elements at this config level
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ChannelCapabilities

Profiles:
    # Different configuration profiles may be encoded here to be specified as parameters to the configtxgen tool

    TwoOrgsOrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *global
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *org1
                    - *org2
    TwoOrgsChannel:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *org1
                - *org2
            Capabilities:
                <<: *ApplicationCapabilities
